dist: trusty
sudo: require
language: ruby
cache: bundler
rvm:
  - 2.4.1

services:
  - docker

before_install:
- docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.4.0-chromium
- docker run --name chrome -d --link selenium-hub:hub selenium/node-chrome:3.4.0-chromium

addons:
  apt:
    packages:
      - google-chrome-unstable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - bundle exec rspec
